server:
  port: 8002
spring:
  application:
    name: cloud-payment-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud_01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 927wcr


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cr.cloud.entities #取别名，当做实体类映射时，会找到当前路径下的类，在mapper.xml中不用在写全限定类名
eureka:
  client:
    register-with-eureka: true #注册到eureka 服务中心
    fetch-registry: true # 抓取服务中心列表信息，单机无所谓，集群必须为true
    # 指定注册到哪里去
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
