server:
  port: 2001
spring:
  application:
    name: seata-order-server
  cloud:
    alibaba:
      seata:
        #自定义事务组名称，要与在file.conf里的名称一致
        tx-service-group: myseata-tx-group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: 927wcr
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
